version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    labels: ["dependencies", "security"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    labels: ["dependencies", "ci"]

  - package-ecosystem: "docker"
    directory: "/scripts"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    labels: ["dependencies", "docker"]
