# Online Latency Benchmark
name: "online-benchmark"
version: "1.0"
type: "online"

model_params:
  name: "meta-llama/Llama-3.1-8B-Instruct"
  temperature: 0.7
  top_p: 0.9
  max_new_tokens: 1024

datasets:
  - name: "latency-test"
    type: "performance"
    path: "cnn_dailymail_train.json"
    samples: 500
    parser:
      prompt: "article"

settings:
  runtime:
    min_duration_ms: 60000 # 1 minutes
    max_duration_ms: 180000 # 3 minutes
    scheduler_random_seed: 42 # For Poisson/distribution sampling
    dataloader_random_seed: 42 # For dataset shuffling

  load_pattern:
    type: "poisson"
    target_qps: 10

  client:
    workers: 4

metrics:
  collect:
    - "throughput"
    - "latency"
    - "ttft"
    - "tpot"

endpoint_config:
  endpoint: "http://localhost:8000"
  api_key: null
  api_type: "openai" # Options: openai or sglang
